name: Build macOS ARM

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [master, release]
  workflow_dispatch:

env:
  MACOSX_DEPLOYMENT_TARGET: 11.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-14
            TARGET: macos
            CMD_BUILD: python3 setup.py bdist_wheel --plat-name macosx_11_0_arm64

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: arch -arm64 brew reinstall zlib

      - name: Setup pyenv
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          MACOSX_DEPLOYMENT_TARGET: 11.0
          PYTHON_CONFIGURE_OPTS: "--enable-framework"
          CFLAGS: "-Wno-implicit-function-declaration"
          LDFLAGS: "-L/usr/local/opt/zlib/lib"
          CPPFLAGS: "-I/usr/local/opt/zlib/include"
          PKG_CONFIG_PATH: "/usr/local/opt/zlib/lib/pkgconfig"
        uses: "gabrielfalcao/pyenv-action@v18"
        with:
            default: "3.9"
            command: pip3 install -U pip3 wheel setuptools

      - name: Built wheel for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD}}

      - name: Upload Python wheel
        uses: actions/upload-artifact@v4
        with:
          name: Python wheel
          path: ${{github.workspace}}/dist/raidionicsseg-*.whl
          if-no-files-found: error

  test:
    needs: build
    strategy:
      matrix:
        os: [macos-14]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}

    steps:
        - name: Set up pyenv using Python ${{ matrix.python-version }}
          uses: "gabrielfalcao/pyenv-action@v18"
          with:
              default: ${{ matrix.python-version }}
              command: pip3 install -U pip3 wheel setuptools

        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: "Python wheel"

        - name: Install wheel
          run: pip3 install --default-timeout=100 --find-links=${{github.workspace}} raidionicsseg-*
          shell: bash

        - name: Test CLI
          run: python3 -m raidionicsseg --help

        - name: Clone repo
          uses: actions/checkout@v4

        - name: Singular unit test
          run: cd ${{github.workspace}}/tests && python3 inference_test.py

#        - name: Test with pytest
#          run: |
#            pip install pytest
#            pytest --verbose tests/
