name: Build macOS

on:
  push:
    branches: [ master,update ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  MACOSX_DEPLOYMENT_TARGET: 10.15

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-11
            TARGET: macos
            CMD_BUILD: python setup.py bdist_wheel --plat-name macosx_10_15_x86_64

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: pip install wheel setuptools

      - name: Built wheel for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD}}

      - name: Upload Python wheel
        uses: actions/upload-artifact@v3
        with:
          name: Python wheel
          path: ${{github.workspace}}/dist/raidionicsseg-*.whl
          if-no-files-found: error

  test:
    needs: build
    strategy:
      matrix:
        os: [macos-11, macos-12]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}

    steps:
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}

        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            name: "Python wheel"

        - name: Install wheel
          run: pip install --upgrade pip
               pip install --find-links=${{github.workspace}} raidionicsseg-*
          shell: bash

        - name: Test CLI
          run: raidionicsseg --help

        - name: Clone repo
          uses: actions/checkout@v1

        - name: Singular unit test
          run: cd ${{github.workspace}}/tests && python inference_test.py

#        - name: Test with pytest
#          run: |
#            pip install pytest
#            pytest --verbose tests/
