name: Build macOS ARM

on:
  push:
    branches: [master,update]
  pull_request:
    branches: [master, release]
  workflow_dispatch:

env:
  MACOSX_DEPLOYMENT_TARGET: 11.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-14
            TARGET: macos
            CMD_BUILD: python -m cibuildwheel --output-dir dist #python3 setup.py bdist_wheel --plat-name macosx_11_0_arm64

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: arch -arm64 brew reinstall zlib

      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build the wheel for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD}}
        env:
          CIBW_BUILD: "cp310-*"
          CIBW_ARCHS_MACOS: "arm64"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_MANYLINUX_I686_IMAGE: manylinux1
          CIBW_TEST_SKIP: "*-macosx_arm64"

      - name: Upload Python wheel
        uses: actions/upload-artifact@v4
        with:
          name: Python wheel
          path: ${{github.workspace}}/dist/raidionicsseg-*.whl
          if-no-files-found: error

  test:
    needs: build
    strategy:
      matrix:
        os: [macos-14]
        python-version: ["3.10", "3.11"]
    runs-on: ${{ matrix.os }}

    steps:
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}

        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: "Python wheel"

        - name: Install wheel
          run: pip3 install --upgrade pip
               pip3 install --default-timeout=100 --find-links=${{github.workspace}} --force-reinstall raidionicsseg-*
          shell: bash

        - name: Test CLI
          run: python3 -m raidionicsseg --help

        - name: Clone repo
          uses: actions/checkout@v4

        - name: Inference unit test with TensorFlow model
          run: cd ${{github.workspace}}/tests && python3 inference_test.py

        - name: Inference unit test with PyTorch model
          run: cd ${{github.workspace}}/tests && python3 inference_test_torch_model.py

#        - name: Test with pytest
#          run: |
#            pip install pytest
#            pytest --verbose tests/
