name: CI Ubuntu

on:
  push:
    branches: [ master, update ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:18.04

    steps:
      - uses: actions/checkout@v3

      - name: Install pip
        run: apt update && apt install -y sudo && sudo apt install -y libpython3-dev python3-pip python3-setuptools

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip3 install wheel setuptools

      - name: Built wheel for Ubuntu
        run: python3 setup.py bdist_wheel --plat-name manylinux1_x86_64

      - name: Upload Python wheel
        uses: actions/upload-artifact@v2
        with:
          name: Python wheel
          path: ${{github.workspace}}/dist/raidionicsseg-*.whl
          if-no-files-found: error

  test:
    needs: build
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:18.04

    steps:
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Download artifact
          uses: actions/download-artifact@master
          with:
            name: "Python wheel"

        - name: Install pip
          run: apt update && apt install -y python3-pip

        - name: Install wheel
          run: pip3 install --find-links=${{github.workspace}} raidionicsseg

        - name: Test CLI
          run: raidionicsseg --help

        - name: Clone repo
          uses: actions/checkout@v1

        - name: Singular unit test
          run: cd ${{github.workspace}}/tests && python inference_test.py

#        - name: Test with pytest
#          run: |
#            pip install pytest
#            pytest --verbose tests/
